aws:
  region: "ap-southeast-2"
  profile: null

s3:
  bucket: "prod-sitetracker-image-store"
  root_prefix: "ODM Duplicate Image/"
  # Performance settings
  # max_jobs_to_process: 5  # Set to a number to limit jobs processed (e.g., 10 for testing)
  timeout_seconds: 300  # 5 minutes timeout for S3 operations

hashing:
  mode: "basic"  # or "advanced"
  resize:
    width: 256
    height: 256

output:
  target: "local_csv"  # local_csv | local_parquet | microsoft_fabric | aws_redshift
  path: "outputs/hash_index"  # base path; extension chosen by target

state:
  path: "outputs/state/seen.json"

duplicates:
  threshold: 5
  bands: 8

