aws:
  region: "ap-southeast-2"
  profile: null

s3:
  bucket: "prod-sitetracker-image-store"
  root_prefix: "ODM Duplicate Image/"
  # Performance settings
  # max_jobs_to_process: 5  # Set to a number to limit jobs processed (e.g., 10 for testing)
  timeout_seconds: 300  # 5 minutes timeout for S3 operations

hashing:
  mode: "basic"  # or "advanced"
  resize:
    width: 256
    height: 256

output:
  target: "local_csv"  # local_csv | local_parquet
  path: 'C:\Users\George.Nizoridis\OneDrive - Service Stream\Documents - Analytics & Insights Team\02 Telco\Projects\SiteTracker - Duplicate Images\Hash_DB_Store\hash_index.csv'

state:
  path: "outputs/state/seen.json"

links:
  enabled: true
  expiry_days: 7
  output:
    target: "local_parquet"
    path: "outputs/links/link_index.parquet"
  state_path: "outputs/state/links.json"
  workers: 16

